/**
 * Export workbook generation tests.
 *
 * Uses `buildXlsxBuffer` (DOM-free, returns ArrayBuffer) so the suite runs
 * in vitest's default node environment without jsdom. We round-trip the
 * generated bytes through SheetJS to verify:
 *   - both Summary and Data sheets exist
 *   - headers and rows survive
 *   - identity-shaped columns are auto-redacted unless admin
 *   - dates are sliced to YYYY-MM-DD
 *   - the summary key/value pairs come through
 */
import { describe, it, expect } from 'vitest';
import * as XLSX from 'xlsx';
import { buildXlsxBuffer, type ExportColumn } from '@/lib/export/xlsx-export';

type TestEmployee = {
  id: string;
  fullName: string;
  identityNumber: string;
  hireDate: string;
  salary: number;
};

const TEST_ROWS: TestEmployee[] = [
  { id: 'emp_1', fullName: 'Alpha One',  identityNumber: '2111111111', hireDate: '2024-01-15T00:00:00Z', salary: 12000 },
  { id: 'emp_2', fullName: 'Beta Two',   identityNumber: '2222222222', hireDate: '2023-06-01',           salary: 9500 },
];

const COLS: ExportColumn<TestEmployee>[] = [
  { header: 'Full Name',        value: (e) => e.fullName },
  { header: 'Identity / Iqama', value: (e) => e.identityNumber },
  { header: 'Hire Date',        value: (e) => e.hireDate, format: 'date' },
  { header: 'Salary',           value: (e) => e.salary },
];

function readWorkbookFromArrayBuffer(ab: ArrayBuffer): XLSX.WorkBook {
  return XLSX.read(ab, { type: 'array' });
}

describe('buildXlsxBuffer', () => {
  it('produces a workbook with Summary + named data sheet', async () => {
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: 'Employees', rows: TEST_ROWS, columns: COLS,
      summary: [
        { label: 'Total', value: TEST_ROWS.length },
        { label: 'Filter', value: 'none' },
      ],
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    expect(wb.SheetNames).toContain('Summary');
    expect(wb.SheetNames).toContain('Employees');
  });

  it('redacts identity columns by default (non-admin)', async () => {
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: 'Employees', rows: TEST_ROWS, columns: COLS,
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets['Employees']!);
    // 21xxxxxx11 — first 2 + last 2, middle masked
    expect(rows[0]?.['Identity / Iqama']).toBe('21xxxxxx11');
    expect(rows[1]?.['Identity / Iqama']).toBe('22xxxxxx22');
    // Non-identity columns untouched
    expect(rows[0]?.['Full Name']).toBe('Alpha One');
    expect(rows[1]?.['Salary']).toBe(9500);
  });

  it('passes identity through when admin (redactIdentity:false)', async () => {
    const ab = await buildXlsxBuffer(
      { filename: 'test', sheet: 'Employees', rows: TEST_ROWS, columns: COLS },
      { redactIdentity: false },
    );
    const wb = readWorkbookFromArrayBuffer(ab);
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets['Employees']!);
    expect(rows[0]?.['Identity / Iqama']).toBe('2111111111');
    expect(rows[1]?.['Identity / Iqama']).toBe('2222222222');
  });

  it('slices date columns to YYYY-MM-DD', async () => {
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: 'Employees', rows: TEST_ROWS, columns: COLS,
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets['Employees']!);
    expect(rows[0]?.['Hire Date']).toBe('2024-01-15');
    expect(rows[1]?.['Hire Date']).toBe('2023-06-01');
  });

  it('summary sheet contains the provided label/value pairs', async () => {
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: 'Employees', rows: TEST_ROWS, columns: COLS,
      summary: [
        { label: 'Total rows', value: 42 },
        { label: 'Status', value: 'active' },
      ],
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    const summary = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets['Summary']!, { header: 1 });
    const flat = summary.flat().map(String);
    expect(flat).toContain('Total rows');
    expect(flat).toContain('42');
    expect(flat).toContain('Status');
    expect(flat).toContain('active');
  });

  it('truncates very-long sheet names to fit Excel 31-char limit', async () => {
    const longName = 'A'.repeat(50);
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: longName, rows: TEST_ROWS, columns: COLS,
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    const dataSheet = wb.SheetNames.find((n) => n !== 'Summary');
    expect(dataSheet?.length).toBeLessThanOrEqual(31);
  });

  it('handles zero rows (export-empty)', async () => {
    const ab = await buildXlsxBuffer({
      filename: 'test', sheet: 'Empty', rows: [], columns: COLS,
    });
    const wb = readWorkbookFromArrayBuffer(ab);
    expect(wb.SheetNames).toContain('Empty');
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets['Empty']!);
    expect(rows).toHaveLength(0);
  });
});
