export const expectedSchema = [
  'SourceFile',
  'ContractNumber',
  'Name',
  'Profession',
  'EmployeeNumber',
  'Nationality',
  'DateOfBirth',
  'IdentityNumber',
  'IDType',
  'IDExpiryDate',
  'Gender',
  'Religion',
  'MaritalStatus',
  'Education',
  'Speciality',
  'IBAN',
  'BankName',
  'Email',
  'MobileNumber',
  'ContractDurationYears',
  'StartDate',
  'EndDate',
  'JoiningDate',
  'BasicSalary',
  'HousingProvided',
  'TransportProvided',
  'HousingAllowance',
  'TransportationAllowance',
  'FoodAllowance',
  'OTAllowance',
  'MastersDegreeAllowance',
  'TotalCashAllowances',
  'GrossCashMonthly'
];

export const schemaAliases = {
  sourcefile: 'SourceFile',
  contractnumber: 'ContractNumber',
  contract_no: 'ContractNumber',
  contractno: 'ContractNumber',
  name: 'Name',
  employeename: 'Name',
  profession: 'Profession',
  jobtitle: 'Profession',
  employeenumber: 'EmployeeNumber',
  employeeno: 'EmployeeNumber',
  nationality: 'Nationality',
  dateofbirth: 'DateOfBirth',
  dob: 'DateOfBirth',
  identitynumber: 'IdentityNumber',
  idnumber: 'IdentityNumber',
  idtype: 'IDType',
  idexpirydate: 'IDExpiryDate',
  gender: 'Gender',
  religion: 'Religion',
  maritalstatus: 'MaritalStatus',
  education: 'Education',
  speciality: 'Speciality',
  specialty: 'Speciality',
  iban: 'IBAN',
  bankname: 'BankName',
  email: 'Email',
  mobilenumber: 'MobileNumber',
  phone: 'MobileNumber',
  contractdurationyears: 'ContractDurationYears',
  startdate: 'StartDate',
  enddate: 'EndDate',
  joiningdate: 'JoiningDate',
  basicsalary: 'BasicSalary',
  housingprovided: 'HousingProvided',
  transportprovided: 'TransportProvided',
  housingallowance: 'HousingAllowance',
  transportationallowance: 'TransportationAllowance',
  foodallowance: 'FoodAllowance',
  otallowance: 'OTAllowance',
  mastersdegreeallowance: 'MastersDegreeAllowance',
  totalcashallowances: 'TotalCashAllowances',
  grosscashmonthly: 'GrossCashMonthly'
};

export const nationalityNormalization = {
  pakistan: 'Pakistani',
  pakistani: 'Pakistani',
  egypt: 'Egyptian',
  egyptian: 'Egyptian',
  saudi: 'Saudi',
  saudiarabia: 'Saudi',
  jordan: 'Jordanian',
  jordanian: 'Jordanian',
  india: 'Indian',
  indian: 'Indian',
  bangladesh: 'Bengali',
  bengali: 'Bengali'
};
